---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: publish_image
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: aptalca/zap2xml
    username:
      from_secret: docker_username
  when:
    ref:
    include:
    - refs/heads/*
    branch:
    - master
    event:
    - push
    - tag

- name: publish-pr
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64-pr
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: aptalca/zap2xml
    username:
      from_secret: docker_username
  when:
    ref:
    include:
    - refs/heads/*
    event:
    - pull_request

- name: publish-branch
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64-dev
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: aptalca/zap2xml
    username:
      from_secret: docker_username
  when:
    ref:
    include:
    - refs/heads/*
    branch:
      exclude:
      - master
    event:
    - push

---
kind: pipeline
name: linux-arm

platform:
  os: linux
  arch: arm

steps:
- name: publish_image
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: Dockerfile.arm
    password:
      from_secret: docker_password
    repo: aptalca/zap2xml
    username:
      from_secret: docker_username
  when:
    ref:
    include:
    - refs/heads/*
    branch:
    - master
    event:
    - push
    - tag

- name: publish-pr
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm-pr
    dockerfile: Dockerfile.arm
    password:
      from_secret: docker_password
    repo: aptalca/zap2xml
    username:
      from_secret: docker_username
  when:
    ref:
    include:
    - refs/heads/*
    event:
    - pull_request

- name: publish-branch
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm-dev
    dockerfile: Dockerfile.arm
    password:
      from_secret: docker_password
    repo: aptalca/zap2xml
    username:
      from_secret: docker_username
  when:
    ref:
    include:
    - refs/heads/*
    branch:
      exclude:
      - master
    event:
    - push

---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: publish_image
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: Dockerfile.aarch64
    password:
      from_secret: docker_password
    repo: aptalca/zap2xml
    username:
      from_secret: docker_username
  when:
    ref:
    include:
    - refs/heads/*
    branch:
    - master
    event:
    - push
    - tag

- name: publish-pr
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64-pr
    dockerfile: Dockerfile.aarch64
    password:
      from_secret: docker_password
    repo: aptalca/zap2xml
    username:
      from_secret: docker_username
  when:
    ref:
    include:
    - refs/heads/*
    event:
    - pull_request

- name: publish-branch
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64-dev
    dockerfile: Dockerfile.aarch64
    password:
      from_secret: docker_password
    repo: aptalca/zap2xml
    username:
      from_secret: docker_username
  when:
    ref:
    include:
    - refs/heads/*
    branch:
      exclude:
      - master
    event:
    - push

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: server
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: manifest.tmpl
    username:
      from_secret: docker_username
  when:
    ref:
    include:
    - refs/heads/*
    branch:
    - master
    event:
    - push
    - tag

depends_on:
- linux-amd64
- linux-arm
- linux-arm64

---
kind: pipeline
name: manifest-pr

platform:
  os: linux
  arch: amd64

steps:
- name: server
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: manifest-pr.tmpl
    username:
      from_secret: docker_username
  when:
    ref:
    include:
    - refs/heads/*
    event:
    - pull_request

depends_on:
- linux-amd64
- linux-arm
- linux-arm64

---
kind: pipeline
name: manifest-dev

platform:
  os: linux
  arch: amd64

steps:
- name: server
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: manifest-dev.tmpl
    username:
      from_secret: docker_username
  when:
    ref:
    include:
    - refs/heads/*
    branch:
      exclude:
      - master
    event:
    - push

depends_on:
- linux-amd64
- linux-arm
- linux-arm64

...
