#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	/config/log/zap2xml

# check zap2xml script
[[ ! -f /config/zap2xml.pl ]] && \
	echo "copy script into the config folder and restart the container" && \
	exit 1

# check variables
if [ -z "$EMAIL" ] || [ -z "$PASSWORD" ]; then
	echo "Please pass your EMAIL and PASSWORD as environment variables in your docker run command. See docker info for more details."
	exit 1
else
  echo "Retrieving email and password from the environment variables"
  echo -e "EMAIL=\"$EMAIL\" PASSWORD=\"$PASSWORD\" EXTRAPARAM=\"$EXTRAPARAM\"" > /app/zap2xml.conf
fi

# set permissions
chown -R abc:abc \
	/app \
	/config
chmod +x \
	/app/zap2xml.sh \
	/config/zap2xml.pl

# run initial retrieval
cd /config
sleep 2
echo "Initial run of zap2xml in progress, check the logs at /config/log/zap2xml/zap2xml.log $(date)"
exec \
	s6-setuidgid abc /app/zap2xml.sh >> /config/log/zap2xml/zap2xml.log 2>&1
